language: java
jdk: oraclejdk11

sudo: required
dist: trusty

env:
  global:
    - JVMCI_VERSION="jvmci-0.46"
    - JVMCI_BASE_JDK8="openjdk1.8.0_172"
    - JVMCI_FILE_JDK8="openjdk-8u172"
  matrix:
    - JDK="jdk8" GATE="style,fullbuild"
    - JDK="jdk8" GATE="build,test" ARCH="32bit"
    - JDK="jdk8" GATE="build,test" ARCH="64bit"
    - JDK="jdk11" GATE="style,fullbuild"
    - JDK="jdk11" GATE="build,test" ARCH="32bit"
    - JDK="jdk11" GATE="build,test" ARCH="64bit"

matrix:
  allow_failures:
    - env: ARCH="64bit"
  fast_finish: true

python:
  - "2.7"
addons:
  apt:
    packages:
      - jq
      - python-pip
      - python-virtualenv
      - wget

install:
  - |
      export MX_PATH=${TRAVIS_BUILD_DIR}/../mx
      git clone --depth 1 https://github.com/graalvm/mx.git ${MX_PATH}
      export PATH=${PATH}:${MX_PATH}
  - |
      if [[ ${GATE} == *style* ]]
      then
        virtualenv venv
        source venv/bin/activate
        pip install astroid==1.1.0
        pip install pylint==1.1.0

        pushd ${TRAVIS_BUILD_DIR}/.. > /dev/null
        local eclipse_tar="ci-dep-eclipse-SDK-4.5.2-linux-gtk-x86_64.tar.gz"
        ${TRAVIS_BUILD_DIR}/scripts/download-file.sh "${eclipse_tar}"
        tar -xzf ${eclipse_tar}
        export ECLIPSE_EXE=$(pwd)/eclipse/eclipse
        popd > /dev/null
      fi
  - |
      if [[ ${GATE} == *fullbuild* ]]
      then
        # Only test JDT on JDK8
        if [[ "${JDK}" == "jdk8" ]]
        then
          export JDT=${MX_PATH}/ecj.jar
          local ecj_tar="ci-dep-ecj-4.5.2.jar"
          ${TRAVIS_BUILD_DIR}/scripts/download-file.sh "${ecj_tar}" "${JDT}"
        fi
      fi
  - |
      if [[ ${GATE} == *test* ]]
      then
        scripts/download-test-image.sh
        if [[ "${JDK}" == "jdk8" ]]
        then
          curl -sSL -o ~/codacy-coverage-reporter.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
          MX_OPTS="--jacocout coverage"
        fi
      fi
  - |
      if [[ "${JDK}" == "jdk8" ]]
      then
        JDK_TAR=${TRAVIS_BUILD_DIR}/../jdk.tar.gz
        curl -sSL -o ${JDK_TAR} https://github.com/graalvm/openjdk8-jvmci-builder/releases/download/${JVMCI_VERSION}/${JVMCI_FILE_JDK8}-${JVMCI_VERSION}-linux-amd64.tar.gz
        tar -C ${TRAVIS_BUILD_DIR}/.. -xzf ${JDK_TAR}
        export JAVA_HOME=${TRAVIS_BUILD_DIR}/../${JVMCI_BASE_JDK8}-${JVMCI_VERSION}
      fi

script:
  - mx --java-home=${JAVA_HOME} --extra-java-homes=/usr/lib/jvm/java-8-oracle gate ${MX_OPTS} --strict-mode --tags ${GATE}

after_success:
  - |
      if [[ ${GATE} == *test* ]] && [[ "${JDK}" == "jdk8" ]]
      then
        bash <(curl -s https://codecov.io/bash)
        java -jar ~/codacy-coverage-reporter.jar report -l Java -r jacoco.xml
      fi
