language: java
jdk: oraclejdk9

sudo: required
dist: trusty

env:
  global:
    - JVMCI_VERSION="jvmci-0.43"
    - JVMCI_BASE_JDK8="openjdk1.8.0_171"
    - JVMCI_FILE_JDK8="openjdk-8u171"
  matrix:
    - JDK="jdk8" GATE="style,fullbuild"
    - JDK="jdk8" GATE="build,test"
    - JDK="jdk9" GATE="style,fullbuild"
    - JDK="jdk9" GATE="build,test"

python:
  - "2.7"
addons:
  apt:
    packages:
      - jq
      - python-pip
      - python-virtualenv
      - wget

install:
  - |
      export MX_PATH=${TRAVIS_BUILD_DIR}/../mx
      git clone https://github.com/graalvm/mx.git ${MX_PATH}
      pushd ${MX_PATH} > /dev/null
      git checkout tags/5.171.0
      popd > /dev/null
      export PATH=${PATH}:${MX_PATH}
  - |
      if [[ ${GATE} == *style* ]]
      then
        virtualenv venv
        source venv/bin/activate
        pip install astroid==1.1.0
        pip install pylint==1.1.0

        export ECLIPSE_TAR=${TRAVIS_BUILD_DIR}/../eclipse.tar.gz
        curl -sSL -o ${ECLIPSE_TAR} https://dl.bintray.com/hpi-swa-lab/GraalSqueak/dependencies/eclipse-SDK-4.5.2-linux-gtk-x86_64.tar.gz
        tar -C ${TRAVIS_BUILD_DIR}/.. -xzf ${ECLIPSE_TAR}
        export ECLIPSE_EXE=${TRAVIS_BUILD_DIR}/../eclipse/eclipse
      fi
  - |
      if [[ ${GATE} == *fullbuild* ]]
      then
        # JDT is not supported on JDK9
        if [ "${JDK}" != "jdk9" ]
        then
          export JDT=${MX_PATH}/ecj.jar
          curl -sSL -o ${JDT} https://dl.bintray.com/hpi-swa-lab/GraalSqueak/dependencies/ecj-4.5.2.jar
        fi
      fi
  - |
      if [[ ${GATE} == *test* ]]
      then
        scripts/download-test-image.sh
        curl -sSL -o ~/codacy-coverage-reporter.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
        MX_OPTS="--jacocout coverage"
      fi
  - |
      if [[ "${JDK}" == "jdk8" ]]
      then
        JDK_TAR=${TRAVIS_BUILD_DIR}/../jdk.tar.gz
        curl -sSL -o ${JDK_TAR} https://github.com/dougxc/openjdk8-jvmci-builder/releases/download/${JVMCI_VERSION}/${JVMCI_FILE_JDK8}-${JVMCI_VERSION}-linux-amd64.tar.gz
        tar -C ${TRAVIS_BUILD_DIR}/.. -xzf ${JDK_TAR}
        export JAVA_HOME=${TRAVIS_BUILD_DIR}/../${JVMCI_BASE_JDK8}-${JVMCI_VERSION}
      fi

script:
  - echo ${JAVA_HOME} && ${JAVA_HOME}/bin/java -version
  - mx --java-home=${JAVA_HOME} gate ${MX_OPTS} --strict-mode --tags ${GATE}

after_success:
  - |
      if [[ ${GATE} == *test* ]]
      then
        bash <(curl -s https://codecov.io/bash)
        jdk_switcher use oraclejdk8 # required for codacy-coverage-reporter
        ${JAVA_HOME}/bin/java -jar ~/codacy-coverage-reporter.jar report -l Java -r jacoco.xml
      fi
