language: java
jdk:
  - oraclejdk8
install:
  - git clone --depth 1 https://github.com/graalvm/mx
before_script:
  - mx/mx -n sforceimports
  - mx/mx -n build
  - test/download-test-image.sh
script:
  - mx/mx -n unittest --verbose --regex trufflesqueak
